name: Build
on:
  push:
    branches:
      - 'chore/ci-build-with-gha'

jobs:
  dependencies:
    runs-on: macos-13
    steps:
        - name: Check out repository code
          uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: '18.16.0'
        - uses: ruby/setup-ruby@v1
          with:
            ruby-version: '3.2.1'
        - name: Install dependencies
          run: bundle install
        - name: Build
          env:
              SAP_ARTIFACTORY_URL: ${{ secrets.SAP_ARTIFACTORY_URL }}
              PIPER_VAULTCREDENTIAL_IDENTITY_TOKEN: ${{ secrets.PIPER_VAULTCREDENTIAL_IDENTITY_TOKEN }}
          run: |
            bundle exec fastlane ios build_community
