# This action automatically extracts the Jira reference from the title of a
# pull request and adds a reference to the pull request to that Jira item.
name: PR - Link to Jira

on:
  pull_request:
    types:
      - edited
      - opened

jobs:
  link:
    uses: kulturpass/kp-gh-actions/.github/workflows/reusable-link-to-jira.yml@v1
    secrets: inherit